variable s3_matrix_models_bucket_name {}
variable glue_job_name1 {}
variable glue_job_name2 {}
variable glue_job_name3 {}
variable lambda_role_arn {}
variable s3_matrix_models_prefixes_list1 {}
variable s3_matrix_models_prefixes_list2 {}
variable s3_matrix_models_prefixes_list3 {}
variable lambda_execute_sql_ddl_name {}
variable s3_resources_bucket_name {}
variable s3_ddl_key {}
variable subnet_ids {}
variable security_group_ids {}
variable secrets_manager_secret_name {}
variable rds_instance_creation_rule_arn {}
variable lambda_trigger_glue_job_name {}

variable lambda_execute_client_group_prediction_name {}
variable lambda_invoke_model1_name {}
variable lambda_invoke_model2_name {}
variable prefix_processing_artifacts {}
variable prefix_sku_catalog {}
variable output_layer {}
variable lambda_train_nltk_model_name {}
variable non_redeeming_clients_glue_job_name {}