variable glue_etl_role {}
variable s3_resources_bucket_name {}
variable secret_manager_id {}
variable private_subnet_id {}
variable glue_security_group_id {}
variable glue_availability_zone {}
variable aurora_cluster_endpoint {}
variable aurora_database_name {}
variable s3_matrix_models_bucket_name {}
variable secrets_manager_secret_name {}
variable prefix_recommender {}
variable prefix_profile {}
variable prefix_churn {}
variable prefix_new_partner {}
variable prefix_re_entry {}